### ISSUE TITLE
Adding Socials in the readme file so that other aspiring contributors can easily join us there

### ISSUE THREAD

**Issue by KlausMikhaelson** [komodorio/helm-charts#108]
Hello, I have seen that every open source projects it gets easier for contributors to get into the community if there are socials in the readme as well, so I would like to add that if it gets approved.
Thank you.

**Comment by KIET7UKE** [comment]
Hey @KlausMikhaelson, I would love to do this assignment.

**Comment by KlausMikhaelson** [comment]
Hey @KIET7UKE thanks but I have already taken it so just working for their approval, you can always search for other bugs in the code !

**Comment by KIET7UKE** [comment]
> Hey @KIET7UKE thanks but I have already taken it so just working for their approval, you can always search for other bugs in the code !

Oh my bad, I got wrong.

**Comment by undera** [comment]
For helm-dashboard, the main repository is https://github.com/komodorio/helm-dashboard, any chart modifications should be done there
