### ISSUE TITLE
Chart deployment failed when enable persistence into true

### ISSUE THREAD

**Issue by IwasawaMasami** [komodorio/helm-charts#146]
Hi, 
  As i mentioned in title, i want to keep my helm-dashboard data . so i enable the persistence option and set the storageClass name.
But the the result is 
` persistentvolume-controller  no persistent volumes available for this claim and no storage class is set`
here is the part of my value setting:
` dashboard:
  allowWriteActions: true
  persistence:
    enabled: true

    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: "openebs-hostpath"

    ## Helm Dashboard Persistent Volume access modes
    ## Must match those of existing PV or dynamic provisioner
    ## Ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    accessModes:
      - ReadWriteOnce

    ## Helm Dashboard Persistent Volume labels
    ##
    labels: {}

    ## Helm Dashboard Persistent Volume annotations
    ##
    annotations: {}

    ## Set path in case you want to use local host path volumes (not recommended in production)
    ##
    hostPath: ""

    ## Helm Dashboard data Persistent Volume size
    ##
    size: 1024M`

Btw, i checked the pvc.yaml in templates, found the value "**storageClassName**" no mapping ,  wonder if there is any possibilities is related with this part?

**Comment by undera** [comment]
Are you sure you have specified the settings correctly? Your code example above looks broken, maybe it has problems with indentation. Please use triple backticks to mark the multiline code block.

**Comment by undera** [comment]
I just checked on my machine with following config, it worked fine:
```dashboard:
    persistence:
        enabled: true
        storageClass: "openebs-hostpath"
```

**Comment by IwasawaMasami** [comment]
Thank for your quickly reply!&nbsp; i will check my side if there any typo.



---Original---
From: "Andrey ***@***.***&gt;
Date: Tue, Feb 7, 2023 23:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [komodorio/helm-charts] Chart deployment failed when enablepersistence into true (Issue #146)




 
I just checked on my machine with following config, it worked fine:
     persistence:         enabled: true         storageClass: "openebs-hostpath"

**Comment by IwasawaMasami** [comment]
> 

Thank you for your checking! could you paste me your yaml for comparing?  i just verified it ,but it's not work, i can make sure of my storage provisioner is ok.

**Comment by IwasawaMasami** [comment]
> > 
> 
> Thank you for your checking! could you paste me your yaml for comparing? i just verified it ,but it's not work, i can make sure of my storage provisioner is ok.

It worked in chart version 0.1.3 (chart version 0.1.2 may not work)
