### ISSUE TITLE
Unable to use komodor

### ISSUE THREAD

**Issue by fbuser1** [komodorio/helm-charts#167]
Hey everyone, I am trying to play with komodor

I tried to run command from welcome window: helm repo add komodorio https://helm-charts.komodor.io ; helm repo update; helm upgrade --install k8s-watcher komodorio/k8s-watcher --set watcher.actions.basic=true --set watcher.actions.advanced=true --set watcher.actions.podExec=true --set metrics.enabled=true --set apiKey=xxx --set watcher.clusterName=default  --wait --timeout=90s && open https://app.komodor.com/main/services

I have created komodor namespace as prerequisite

Seems like something went wrong:

 Namespace "komodor" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "k8s-watcher"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "komodor"

I use helm 3.10.1

**Comment by undera** [comment]
Hi,
You should not create `komodor` namespace manually. Helm chart does it itself. 

You have 2 options what to do now:

1.  Do `kubectl delete namespace komodor` and repeat the process
2. Add `--set createNamespace=false` to your helm command

I strongly recommend using option #1
