### ISSUE TITLE
Supervisor container sets resources to same value as watcher

### ISSUE THREAD

**Issue by sherif-fanous** [komodorio/helm-charts#291]
There is a bug in the `komodor-agent` helm chart in https://github.com/komodorio/helm-charts/blob/9af15653debf4280c8a0d9063d86616d054e6bee/charts/komodor-agent/templates/watcher/_containers.tpl#L81 where the resources for the `supervisor` container are set to those of the `watcher` instead of the `supervisor`

Should be fixed to `resources: {{ toYaml .Values.components.komodorAgent.supervisor.resources | trim | nindent 4 }}`

**Comment by nirbenator** [comment]
thanks! on it
