### ISSUE TITLE
enableMemLimitChecks cannot be enabled.

### ISSUE THREAD

**Issue by sando38** [komodorio/helm-charts#324]
Hello, 

if one wants to enable `.Values.capabilities.events.enableMemLimitChecks` , the created `Volume` does not have the correct containerName: `k8s-watcher`

https://github.com/komodorio/helm-charts/blob/1da91fb958dc822649e89ab36eccb514f16346b8/charts/komodor-agent/templates/watcher/_volumes.tpl#L17

It uses the chartName `komodor-agent` instead.

**Comment by Moran-k** [comment]
Hi @sando38,

Thank you for reporting the issue with our Helm chart. We appreciate your feedback. We will fix the problem and include the solution in our next release.
